version: '3'

services:
  mysql:
    build: ./sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=au
    ports:
    - "3308:3306"

  au:
    build: .
    depends_on:
      - mysql
    command: bash -c "./wait-for-it.sh mysql:3306 --strict --timeout=300 -- node index.js"

    ports:
      - "3001:3001"

networks:
  default: